### ISSUE TITLE
Dev environment

### ISSUE THREAD

**Issue by Akola-Mbey-Denis** [niki-amini-naieni/instantcalibration#1]
Hi

Thanks for this work

Please can you provide the python dependencies requirement file for your development environment to replicate your results in the main paper.

Best,
Denis

**Comment by niki-amini-naieni** [comment]
Hi @Akola-Mbey-Denis, thank you for your interest! I have updated the README.md with instructions on how to replicate the results in the main paper. The instructions include information on how to set up the development environment as well.
